import { getModelForClass } from "@typegoose/typegoose";
import { Access } from "./Access/Access";
import { Announcement } from "./Announcement/Announcement";
import { Article } from "./Article/Article";
import { ArticleRestriction } from "./ArticleRestriction/ArticleRestriction";
import { Category } from "./Category";
import { Geolocation } from "./GeoLocation/Geolocation";
import { Institution } from "./Institution/Institution";
import { IpLocation } from "./IpLocation/IpLocation";
import { IpRange } from "./IpRange/IpRange";
import { Location } from "./Location/Location";
import { Order } from "./Order/Order";
import { Page } from "./Page/Page";
import { Post } from "./Post/Post";
import { PromoCode } from "./PromoCode/PromoCode";
import { PublicationRequest } from "./PublicationRequest/PublicationRequest";
import { Redirect } from "./Redirect";
import { SignInToken } from "./SiginInToken/SignInToken";
import { Specialty } from "./Specialty/Specialty";
import { TemporaryAccess } from "./TemporaryAccess/TemporaryAccess";
import { TriageQueue } from "./TriageQueue/TriageQueue";
import { Media } from "./Media/Media";
import { User } from "./User";
import { UserType } from "./UserType/UserType";
import { StripePrice } from "./Price/StripePrice";
import { Translation } from "./Translation/Translation";
import { NewArticleVote } from "./NewArticleVote/NewArticleVote";
import { SiteSetting } from "./SiteSetting/SiteSetting";
import { ScienceOpenXml } from "./ScienceOpen/ScienceOpenXml";
import { StripePromoCode } from "./StripeCoupons/StripePromoCode";
import { ClosedAnnouncement } from "./Announcement/ClosedAnnouncement";
import { TrialSettings } from "./TrialSettings/TrialSettings";
import { Feedback } from "./Feedback/Feedback";
import { FeedbackQuestion } from "./Feedback/FeedbackQuestion";
import { FeedbackSettings } from "./Feedback/FeedbackSettings";
import { Payment } from "./PaymentHistory/Payment";
import { Country } from "./Country/Country";
import { AnnouncementView } from "./Announcement/AnnouncementView";

export const OrderModel = getModelForClass(Order);
export const UserModel = getModelForClass(User);
export const LocationModel = getModelForClass(Location);
export const InstitutionModel = getModelForClass(Institution);
export const CategoryModel = getModelForClass(Category);
export const ArticleModel = getModelForClass(Article);
export const TriageQueueModel = getModelForClass(TriageQueue);
export const PageModel = getModelForClass(Page);
export const PostModel = getModelForClass(Post);
export const UserTypeModel = getModelForClass(UserType);
export const IpRangeModel = getModelForClass(IpRange);
export const GeolocationModel = getModelForClass(Geolocation);
export const SpecialtyModel = getModelForClass(Specialty);
export const AccessModel = getModelForClass(Access);
export const IpLocationModel = getModelForClass(IpLocation);
export const ArticleRestrictionModel = getModelForClass(ArticleRestriction);
export const RedirectModel = getModelForClass(Redirect);
export const SigninTokenModel = getModelForClass(SignInToken);
export const TemporaryAccessModel = getModelForClass(TemporaryAccess);
export const AnnouncementModel = getModelForClass(Announcement);
export const AnnouncementViewModel = getModelForClass(AnnouncementView);
export const ClosedAnnouncementsModel = getModelForClass(ClosedAnnouncement);
export const PromoCodeModel = getModelForClass(PromoCode);
export const PublicationRequestModel = getModelForClass(PublicationRequest);
export const MediaModel = getModelForClass(Media);
export const PriceModel = getModelForClass(StripePrice);
export const TranslationModel = getModelForClass(Translation);
export const NewArticleVoteModel = getModelForClass(NewArticleVote);
export const SiteSettingModel = getModelForClass(SiteSetting);
export const ScienceOpenXmlModel = getModelForClass(ScienceOpenXml);
export const StripePromoCodeModel = getModelForClass(StripePromoCode);
export const TrialSettingsModel = getModelForClass(TrialSettings);
export const FeedbackModel = getModelForClass(Feedback);
export const FeedbackQuestionModel = getModelForClass(FeedbackQuestion);
export const FeedbackSettingModel = getModelForClass(FeedbackSettings);
export const PaymentModel = getModelForClass(Payment);

export const CountryModel = getModelForClass(Country);
